### ISSUE TITLE
ERR_MODULE_NOT_FOUND: lodash/merge

### ISSUE THREAD

**Issue by waptik** [sachinraja/trpc-playground#13]
Hey! I found your project interesting and wanted to give it a try. I copied and pasted the code from your example and I'm facing the error below:

```sh
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'drive:\path\to\project\node_modules\lodash\merge' imported from drive:\path\to\project\node_modules\trpc-playground\dist\chunk-GNRAL62P.js
Did you mean to import lodash/merge.js?
```

package version: ^0.1.5
nextjs version: 12.1.4

**Comment by sachinraja** [comment]
Just published a new version trpc-playground@0.1.6 that should fix this.
