### ISSUE TITLE
Moving to trpc-v10

### ISSUE THREAD

**Issue by MatsDK** [sachinraja/trpc-playground#24]
Currently, trpc-playground won't work if you are using a trpc-v10 server. I created this issue to discuss on how/when we should convert to using trpc-v10.

I think it would be better if we moved to a structure for writing queries like this:
```typescript
await trpc.users.byId.query({ userId })
```
Instead of
```typescript
await query("user.byId", { userId })
```

What do you think about this? Should we wait until v10 is released?
I am happy to work on this.

**Comment by sachinraja** [comment]
We can definitely do this now. Feel free to do a PR on the `next` branch! I'll release it on the `next` npm tag.

**Comment by sachinraja** [comment]
available at `trpc-playground@next`
