### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_def')

### ISSUE THREAD

**Issue by kentetics** [sachinraja/trpc-playground#32]
Hello! I'm not sure what's the problem here but I'm having trouble setting it up.

![image](https://user-images.githubusercontent.com/41656606/202889056-09957d53-f715-4f65-abd5-e155039efc7e.png)

I'm getting error from this function:

```
// src/zod-resolve-types.ts
var joinQueries = (functionName, queries) => {
  const queryNames = [];
  const queryTypes = Object.entries(queries).map(([name, query]) => {
    const stringName = `'${name}'`;
    queryNames.push(stringName);
    if (!query.inputParser._def)
      return `QueryName extends ${stringName} ? [undefined?]`;
    const { node } = zodToTs2(query.inputParser);
    const inputType = printNode2(node);
    const queryType = `QueryName extends ${stringName} ? [${inputType}]`;
    return queryType;
  });
  const filteredQueryTypes = queryTypes.filter((value) => typeof value === "string");
  const joinedQueryNames = queryNames.join(" | ");
  const args = ["name: QueryName"];
  const joinedQueryTypes = `${filteredQueryTypes.join(" : ")} : never`;
  args.push(`...args: ${joinedQueryTypes}`);
  return `declare function ${functionName}<QueryName extends ${joinedQueryNames}>(${args.join(",")}): void`;
};
```

I tried downgrading my node version (from 18 lts to 16) yet no luck.

**Comment by MatsDK** [comment]
Hello, I think this is happening because you are using `trpc-v10` and `trpc-playground` is not. You can try installing `trpc-playground@next` for now.

**Comment by sachinraja** [comment]
I think we're releasing v10 Monday (tomorrow) so I'll wait until then and then make v10 the default here

**Comment by kentetics** [comment]
> Hello, I think this is happening because you are using `trpc-v10` and `trpc-playground` is not. You can try installing `trpc-playground@next` for now.
> 
> @sachinraja is it possible to set the `next` branch to default?

Thanks, got it working! I'll reinstall the official once trpc-v10 is supported. You guys are amazing! cheers!

**Comment by sachinraja** [comment]
done (albeit very late...). `trpc-playground@latest` supports v10
