### ISSUE TITLE
Bring back option turning request batching off

### ISSUE THREAD

**Issue by Christopher-Stevers** [sachinraja/trpc-playground#56]
I noticed previous versions had an option to batch requests, could you add that back to `1.0.0`.

**Comment by MatsDK** [comment]
The batching option was removed in [this commit](https://github.com/sachinraja/trpc-playground/commit/d226d7b5829b79cce8bee3f70d6635f2f76fd796#diff-c6e2633179c18a8a604c321ac2808738fa30814bb95da642ff3f28d59eb81190), but it seems like a `httpBatchLink` was added [_here_](https://github.com/sachinraja/trpc-playground/commit/d226d7b5829b79cce8bee3f70d6635f2f76fd796#diff-67d408760f40caae371f2a68f87bc0fdd45b81e75dc93e2b82393153e494ac29). So if you want to batch requests you should be able to do this:
```ts
await Promise.all([
  trpc.getGreeting.query({ name }),
  trpc.getFarewell.query({ name }),
])
```
Hopefully this helps.
